name: get_storage
description: A fast, extra light and synchronous key-value storage written entirely in Dart
version: 2.0.3
homepage: https://github.com/jonataslaw/get_storage

publish_to: 'none'

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get:
    git:
      url: https://github.com/wliu6v/getx.git
      ref: metaforo
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: